### ISSUE TITLE
Add DSA questions, approach to solve them and intuition of the solution

### ISSUE THREAD

**Issue by Anurag127001** [Kushal997-das/Hacktoberfest-2024#129]
add more DSA questions and intuition behind the solution for them and approach for right solution

**Comment by Sofiyan-coder** [comment]
Hi @Anurag127001  , could you please assign this issue to me? I'd love to contribute and start my open source journey with this project!

**Comment by dauntless05** [comment]
hi can please assign it to me !!
thanks

**Comment by Kushal997-das** [comment]
@Sofiyan-coder 

When opening an issue, please include a detailed description. 📝

Don’t forget to star this repo if you haven’t already! ⭐️

After we assign your issue, feel free to submit a Pull Request (PR) under the hacktoberfest label. 🚀

Thanks for your contributions! 🙌

**Comment by NimraAslamkhan** [comment]
Hi there!

I am the Mentor of this project .
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

Please adhere to the existing guidelines.
No additional rules, thanks!
Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).
Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an invalid label.

Looking forward to your contributions!
