### ISSUE TITLE
[Rules] Issues

### ISSUE THREAD

**Issue by Kushal997-das** [Kushal997-das/Hacktoberfest-2024#143]
<h3>Contribution Guidelines 🌟</h3>

When opening an issue, please include a detailed description. 📝

Don’t forget to star ⭐️ this repo if you haven’t already! 

After we assign your issue, feel free to submit a Pull Request (PR) under the `hacktoberfest` . 🚀

Thanks for your contributions! 🙌

**Comment by NimraAslamkhan** [comment]
Hi there!

I am the Mentor of this project .
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

Please adhere to the existing guidelines.
No additional rules, thanks!
Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).
Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an invalid label.

Looking forward to your contributions!
