### ISSUE TITLE
Tic Tac Toe Game

### ISSUE THREAD

**Issue by pritum-4** [Kushal997-das/Hacktoberfest-2024#145]
This issue is intended to build a Tic Tac Toe game.

The game uses Java Swing and Java AWT concepts to build the project.

**Comment by pritum-4** [comment]
Contributing to this repo under hacktoberfest.

**Comment by Aastha7078** [comment]
I want to work on this issue @pritum-4

**Comment by Kushal997-das** [comment]
@pritum-4 Hi, This repo do not demand for this kinda issue , kindly check [this](https://github.com/Kushal997-das/Hacktoberfest-2024?tab=readme-ov-file#hacktoberfest-2024-tasks-)
