### ISSUE TITLE
Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by Shreyashahu** [Kushal997-das/Hacktoberfest-2024#146]
Best Time to Buy and Sell Stock :
  - Create a new folder "Stock-Buy-&-Sell" within the Beginner Level folder.
  - Add the Markdown file containing the LeetCode question "Best Time to Buy and Sell Stock" with a clear problem statement and example.
  - Also add a C++ solution file for the problem.

Update data.json :
  - Will add my name and GitHub username to the list of contributors.
  - Ensure the contributor information follows the same format as existing entries for consistency.

Motivation:
  - Contribute a well-known algorithmic problem to enhance the repository’s value for new learners.
  - Update the data.json to reflect my contributions to this project.

**Comment by Aastha7078** [comment]
can u assign it to me @Shreyashahu

**Comment by NimraAslamkhan** [comment]
Hi there!

I am the Mentor of this project .
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

Please adhere to the existing guidelines.
No additional rules, thanks!
Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).
Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an invalid label.

Looking forward to your contributions!
