### ISSUE TITLE
Adding solution for Registration System problem

### ISSUE THREAD

**Issue by dauntless05** [Kushal997-das/Hacktoberfest-2024#152]
PROBLEM DESCRIPTION

You need to build a registration system for a new email service. Each time a user requests a username, the system checks if it already exists:

If the username is new, the system responds with "OK" and adds it to the database.
If the username exists, the system appends the smallest available number to the name (e.g., "name1", "name2", etc.) and stores this new username.
Input:

First line: an integer n (1 ≤ n ≤ 105) representing the number of registration requests.
Next n lines: each contains a string (up to 32 lowercase characters), the username request.
Output: For each request, output "OK" or the new generated username.

Input
6
first
first
second
second
third
third

Output
OK
first1
OK
second1
OK
third1

I would like to contribute to this repo under hacktoberfest, kindly assign me this issue

**Comment by Kushal997-das** [comment]
@dauntless05 Read [this](https://github.com/Kushal997-das/Hacktoberfest-2024?tab=readme-ov-file#hacktoberfest-2024-tasks-) We do not need this kinda issue here .
