### ISSUE TITLE
Add Solution for "3 Sum" Problem 

### ISSUE THREAD

**Issue by Visha17** [Kushal997-das/Hacktoberfest-2024#154]
This issue aims to add a coding problem titled "3 Sum" along with its solution to the repository.

**Problem Statement:**

Description: Given an array nums of n integers, find all unique triplets that sum to zero.

Constraints: The solution should not return duplicate triplets.

Example:
Input: [-1, 0, 1, 2, -1, -4]
Output: [[-1, 0, 1], [-1, -1, 2]]

I would like to contribute to this repo under hacktoberfest, kindly assign me this issue @Kushal997-das

**Comment by uddipbisht** [comment]
![Screenshot 2024-10-04 023244](https://github.com/user-attachments/assets/4a83bc2e-9922-44d9-82d4-387851d521c5)
*****  add solution for 3 sum problem*****
#include <iostream>
#include <vector>
#include <algorithm>

using namespace std;

class ThreeSum {
public:
    vector<vector<int>> threeSum(vector<int>& nums) {
        sort(nums.begin(), nums.end());
        vector<vector<int>> results;
        
        for (int i = 0; i < static_cast<int>(nums.size()) - 2; i++) {
            if (i > 0 && nums[i] == nums[i - 1]) {
                continue;
            }
            
            int left = i + 1;
            int right = nums.size() - 1;
            
            while (left < right) {
                int currentSum = nums[i] + nums[left] + nums[right];
                
                if (currentSum == 0) {
                    results.emplace_back(vector<int>{nums[i], nums[left], nums[right]});
                    
                    while (left < right && nums[left] == nums[left + 1]) left++;
                    while (left < right && nums[right] == nums[right - 1]) right--;
                    
                    left++;
                    right--;
                } else if (currentSum < 0) {
                    left++;
                } else {
                    right--;
                }
            }
        }
        
        return results;
    }
};

int main() {
    ThreeSum solution;
    vector<int> nums = {-1, 0, 1, 2, -1, -4};
    
    vector<vector<int>> triplets = solution.threeSum(nums);
    
    cout << "Triplets that sum to zero:" << endl;
    for (const auto& triplet : triplets) {
        cout << "[";
        for (size_t i = 0; i < triplet.size(); ++i) {
            cout << triplet[i];
            if (i < triplet.size() - 1) cout << ", ";
        }
        cout << "]" << endl;
    }
    
    return 0;
}

**Comment by uddipbisht** [comment]
#include <iostream>
#include <vector>
#include <algorithm>

using namespace std;

class ThreeSum {
public:
    vector<vector<int>> threeSum(vector<int>& nums) {
        sort(nums.begin(), nums.end());
        vector<vector<int>> results;
        
        for (int i = 0; i < static_cast<int>(nums.size()) - 2; i++) {
            if (i > 0 && nums[i] == nums[i - 1]) {
                continue;
            }
            
            int left = i + 1;
            int right = nums.size() - 1;
            
            while (left < right) {
                int currentSum = nums[i] + nums[left] + nums[right];
                
                if (currentSum == 0) {
                    results.emplace_back(vector<int>{nums[i], nums[left], nums[right]});
                    
                    while (left < right && nums[left] == nums[left + 1]) left++;
                    while (left < right && nums[right] == nums[right - 1]) right--;
                    
                    left++;
                    right--;
                } else if (currentSum < 0) {
                    left++;
                } else {
                    right--;
                }
            }
        }
        
        return results;
    }
};

int main() {
    ThreeSum solution;
    vector<int> nums = {-1, 0, 1, 2, -1, -4};
    
    vector<vector<int>> triplets = solution.threeSum(nums);
    
    cout << "Triplets that sum to zero:" << endl;
    for (const auto& triplet : triplets) {
        cout << "[";
        for (size_t i = 0; i < triplet.size(); ++i) {
            cout << triplet[i];
            if (i < triplet.size() - 1) cout << ", ";
        }
        cout << "]" << endl;
    }
    
    return 0;
}

**Comment by ghost** [comment]
Thank you.i'll start working on this!

**Comment by ghost** [comment]
I have linked pull request for this https://github.com/Kushal997-das/Hacktoberfest-2024/pull/187.Pls merge @Kushal997-das

**Comment by NimraAslamkhan** [comment]
Hi there!

I am the Mentor of this project .
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

Please adhere to the existing guidelines.
No additional rules, thanks!
Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).
Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an invalid label.

Looking forward to your contributions!
