### ISSUE TITLE
Tower of Hanoi

### ISSUE THREAD

**Issue by Speedysays01** [Kushal997-das/Hacktoberfest-2024#156]
This is a classic problem in C programming. It's a great way to learn recursion.
Please assign me this issue under Hacktoberfest 2024.

**Comment by Satyam-nitp** [comment]
Please assign this to me @Kushal997-das

**Comment by NimraAslamkhan** [comment]
Hi there!

I am the Mentor of this project .
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

Please adhere to the existing guidelines.
No additional rules, thanks!
Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).
Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an invalid label.

Looking forward to your contributions!
