### ISSUE TITLE
Add Solution for "Container with most Water" Problem #157

### ISSUE THREAD

**Issue by dhruvjain23** [Kushal997-das/Hacktoberfest-2024#157]
This issue aims to add a coding problem titled "Container with most Water" along with its solution to the repository.

### Problem Statement:
You are given an integer array height of length n. There are n vertical lines drawn such that the two endpoints of the ith line are (i, 0) and (i, height[i]).

Find two lines that together with the x-axis form a container, such that the container contains the most water.

Return the maximum amount of water a container can store.
## Example 1: 
-  **Input: height** = [1,8,6,2,5,4,8,3,7]

- **Output**: 49

- **Explanation**: The above vertical lines are represented by array [1,8,6,2,5,4,8,3,7]. In this case, the max area of water (blue section) the container can contain is 49.

I sole this problem in O(N) complexity.

I would like to contribute to this repo under hacktoberfest, kindly assign me this issue. @Kushal997-das

**Comment by NimraAslamkhan** [comment]
Hi there!

I am the Mentor of this project .
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

Please adhere to the existing guidelines.
No additional rules, thanks!
Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).
Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an invalid label.

Looking forward to your contributions!
