### ISSUE TITLE
Add Solution for "Number of Days in a Month" Problem

### ISSUE THREAD

**Issue by neyhere07** [Kushal997-das/Hacktoberfest-2024#161]
This issue aims to add a coding problem named <strong>Number of Days in a Month</strong> along with its solution to the repository.<hr>

### Problem Statement:

<div>Input the number of the month, calculate the number of days present in that particular month.<br><strong>Note: </strong>Consider non-leap year.<br><br>
  <strong>Example 1: </strong><br><pre><strong>Input: </strong>10<br><strong>Output: </strong>31<br><strong>Explaination: </strong>October has 31 days</pre>
  <strong>Example 2: </strong><br><pre><strong>Input: </strong>2<br><strong>Output: </strong>28<br><strong>Explaination: </strong>February has 28 days</pre>
  <strong>Example 3: </strong><br><pre><strong>Input: </strong>11<br><strong>Output: </strong>30<br><strong>Explaination: </strong>November has 30 days</pre><br>
<strong>Contraints: </strong><br>1 <= month <= 12
</div>
<hr>
@Kushal997-das I would like to contribute this problem to this repository under Hacktoberfest 2024, kindly assign me this issue!

**Comment by uddipbisht** [comment]
![Screenshot 2024-10-04 023907](https://github.com/user-attachments/assets/7e9dfb1a-a90a-4941-bc47-c3683e381383)

**Comment by uddipbisht** [comment]
import java.io.*;
import java.util.*;
public class Main {
    public static void main(String args[]) {
        Scanner sc = new Scanner(System.in);
        int n = sc.nextInt();
        if(n==4 || n==6 || n==9 || n==11){
            System.out.println("30");
        }
        else if(n==2){
            System.out.println("28");
        }
        else{
            System.out.println("31");
        }
    }
}

**Comment by NimraAslamkhan** [comment]
Hi there!

I am the Mentor of this project .
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

Please adhere to the existing guidelines.
No additional rules, thanks!
Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).
Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an invalid label.

Looking forward to your contributions!
